"""
TreppWire RAG System

This script implements a Retrieval Augmented Generation (RAG) system using LangChain and OpenAI's embeddings.
It allows users to ask questions and receive answers based on data processed from S3 and indexed using a vector database.

Dependencies:
-------------
- langchain_openai: For OpenAI embeddings and API integration.
- utils_rag: Custom utilities for managing secrets, OpenAI client, S3 data loading, and TreppWire data handling.
- config: Configuration parameters for the system.

Usage:
------
Run the script from the command line with the following argument:
    --question: The question you want to ask the TreppWire RAG system.

Example:
    python training.py --question "What is the recent price of Flagler Corporate Center loan?"
"""


import os, json
from langchain_openai import OpenAIEmbeddings
from utils_rag import SecretManager, OpenAIClient, S3ParquetLoader, TpwireDataLoader, tpwireRAG
from config import SECRET_NAME, BUCKET_NAME, PREFIX, MODEL, EMBED_MODEL_NAME, K
import argparse



def main(input_question):
    """
    Main function to process a user question and return an answer from the TreppWire RAG system.

    Args:
        input_question (str): The question to be answered by the model.

    Returns:
        str: The answer generated by the model in response to the input question.
    """
    
    secret_manager = SecretManager(secret_name=SECRET_NAME)
    os.environ['OPENAI_API_KEY'] = secret_manager.get_secret('OPENAI_API_KEY')
    
    embed = OpenAIEmbeddings(model=EMBED_MODEL_NAME) # Create embeddings for indexing documents
    
    openai_client = OpenAIClient(model=MODEL)

    # S3 parquet loader
    s3_parquet_loader = S3ParquetLoader(bucket_name=BUCKET_NAME, prefix=PREFIX)

    # Import TreppWire data
    tpwire_loader = TpwireDataLoader(bucket_name=BUCKET_NAME, prefix=PREFIX)

    # Initialize treppwire RAG
    tpwire_RAG = tpwireRAG(embed=embed)
    
    
    tpwire_df = tpwire_loader.process_data("tpwire_flags.parquet")
    # index_tb = index_document(tpwire_df, embed)
    # index_tb = tpwire_RAG.index_document(tpwire_df)
    # index_tb.to_parquet('treppwire_index_tb.parquet')
    # index_tb = pd.read_parquet('treppwire_index_tb.parquet')
    index_tb = s3_parquet_loader.load_s3_parquet('treppwire_index_tb.parquet')
    
    tpwire_RAG.build_vec_db(index_tb=index_tb)
    
    search_text = 'What is the recent price of Flagler Corporate Center loan?'
    relevant_contents, prompt = tpwire_RAG.generate_context_prompt(search_text=search_text, K=K)
    response = openai_client.get_completion(message=prompt)
    return json.loads(response.choices[0].message.content)['Answer']
    
    
    
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Ask a question to the TreppWire RAG system')
    parser.add_argument('--question', metavar='question', required=True,
                        help='The question you want to ask')
    args = parser.parse_args()
    print(f"The answer is: {main(args.question)}")