FROM python:3.10.8-slim-bullseye

ARG DSBUCKETNAME
ENV DSBUCKETNAME=$DSBUCKETNAME

ARG INPUTBUCKETNAME
ENV INPUTBUCKETNAME=$INPUTBUCKETNAME

ARG OUTPUTBUCKETNAME
ENV OUTPUTBUCKETNAME=$OUTPUTBUCKETNAME

ARG DEPLOYENV
ENV DEPLOYENV=$DEPLOYENV

ARG MODERNPRODUCTIONCROSSACCOUNTNUM
ENV MODERNPRODUCTIONCROSSACCOUNTNUM=$MODERNPRODUCTIONCROSSACCOUNTNUM

COPY ./requirements.txt /
RUN pip install --upgrade pip
RUN pip3 install --no-cache-dir -r requirements.txt
COPY /src/trepp/ /

CMD ["python",  "-m", "proforma_financials.inference"]
